"""init_db

Revision ID: 164399dd5ee8
Revises: 
Create Date: 2026-06-20 12:35:17.917486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164399dd5ee8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_ENVIO', 'ENVIADO', 'PROCESSANDO', 'AGUARDANDO_CONFIRMACAO', 'EM_ANALISE', 'APROVADO', 'AGUARDANDO_REENVIO', name='statusdocumento'), nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('versao_atual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['versao_atual_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('obrigatorio_base', sa.Boolean(), nullable=False),
    sa.Column('exige_maioridade', sa.Boolean(), nullable=False),
    sa.Column('exige_frente_verso', sa.Boolean(), nullable=False),
    sa.Column('sexo_obrigatorio', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('CANDIDATO', 'SECRETARIA', name='tipousuario'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('versoes_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analises_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APROVADO', 'REJEITADO', name='statusanalise'), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['secretaria_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arquivos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('lado', sa.Enum('FRENTE', 'VERSO', 'UNICO', name='lado'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_DOCUMENTOS', 'DOCUMENTACAO_EM_PROCESSAMENTO', 'DOCUMENTACAO_PENDENTE', 'EM_ANALISE', 'CORRECAO_SOLICITADA', 'APROVADA', 'INDEFERIDA', name='statuscandidatura'), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_resultados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('dados_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_identificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nome_pai', sa.String(length=255), nullable=False),
    sa.Column('nome_mae', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidatura_id')
    )
    op.create_table('dados_residencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidatura_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados_residencia')
    op.drop_table('dados_identificacao')
    op.drop_table('ocr_resultados')
    op.drop_table('candidaturas')
    op.drop_table('arquivos_documento')
    op.drop_table('analises_documento')
    op.drop_table('versoes_documento')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_documento')
    op.drop_table('documento')
    # ### end Alembic commands ###
