"""add documentos

Revision ID: 30bc9bee621e
Revises: ba205635334e
Create Date: 2026-05-15 10:36:28.258336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bc9bee621e'
down_revision: Union[str, Sequence[str], None] = 'ba205635334e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('obrigatorio_base', sa.Boolean(), nullable=False),
    sa.Column('exige_maioridade', sa.Boolean(), nullable=False),
    sa.Column('sexo_obrigatorio', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_ENVIO', 'ENVIADO', 'PROCESSANDO', 'PROCESSADO', 'APROVADO', 'REJEITADO', name='statusdocumento'), nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento')
    op.drop_table('tipos_documento')
    # ### end Alembic commands ###
