"""adicionar tabelas de dados oficiais

Revision ID: 6f4763311368
Revises: 89d7cab6b25f
Create Date: 2026-06-19 00:58:35.127560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4763311368'
down_revision: Union[str, Sequence[str], None] = '89d7cab6b25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_identificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nome_pai', sa.String(length=255), nullable=False),
    sa.Column('nome_mae', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidatura_id')
    )
    op.create_table('dados_residencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidatura_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados_residencia')
    op.drop_table('dados_identificacao')
    # ### end Alembic commands ###
