"""initial schema

Revision ID: b4a578e1ea6d
Revises: 
Create Date: 2026-05-22 22:24:22.946703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a578e1ea6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('CANDIDATO', 'SECRETARIA', name='tipousuario'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_ENVIO', 'AGUARDANDO_PROCESSAMENTO', 'AGUARDANDO_ANALISE', 'EM_ANALISE', 'APROVADO', 'INDEFERIDO', name='statuscandidatura'), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('obrigatorio_base', sa.Boolean(), nullable=False),
    sa.Column('exige_maioridade', sa.Boolean(), nullable=False),
    sa.Column('sexo_obrigatorio', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_ENVIO', 'ENVIADO', 'PROCESSANDO', 'AGUARDANDO_CONFIRMACAO', 'PROCESSADO', 'EM_ANALISE', 'APROVADO', 'REJEITADO', name='statusdocumento'), nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versoes_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analises_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motivo_rejeicao', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['secretaria_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arquivos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('lado', sa.Enum('FRENTE', 'VERSO', 'UNICO', name='lado'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_resultados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('dados_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versoes_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_resultados')
    op.drop_table('arquivos_documento')
    op.drop_table('analises_documento')
    op.drop_table('versoes_documento')
    op.drop_table('documento')
    op.drop_table('tipos_documento')
    op.drop_table('candidaturas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('categorias_documento')
    # ### end Alembic commands ###
