"""init

Revision ID: ba205635334e
Revises: 
Create Date: 2026-05-14 01:16:35.943508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba205635334e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('CANDIDATO', 'SECRETARIA', name='tipousuario'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', name='sexo'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_ENVIO', 'AGUARDANDO_PROCESSAMENTO', 'AGUARDANDO_ANALISE', 'EM_ANALISE', 'APROVADO', 'INDEFERIDO', name='statuscandidatura'), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidaturas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
