"""estrutura documental inicial

Revision ID: e747b8610060
Revises: f3449a189bb4
Create Date: 2026-05-21 18:05:45.552048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e747b8610060'
down_revision: Union[str, Sequence[str], None] = 'f3449a189bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documento', 'status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('PENDENTE_ENVIO', 'ENVIADO', 'PROCESSANDO', 'AGUARDANDO_CONFIRMACAO', 'PROCESSADO', 'EM_ANALISE', 'APROVADO', 'REJEITADO', name='statusdocumento'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documento', 'status',
               existing_type=sa.Enum('PENDENTE_ENVIO', 'ENVIADO', 'PROCESSANDO', 'AGUARDANDO_CONFIRMACAO', 'PROCESSADO', 'EM_ANALISE', 'APROVADO', 'REJEITADO', name='statusdocumento'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
