"""adiciona versao_atual_id em documento

Revision ID: e7d8c013f3a2
Revises: 044e958ebf46
Create Date: 2026-05-24 02:59:35.403413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8c013f3a2'
down_revision: Union[str, Sequence[str], None] = '044e958ebf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'documento'
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'versao_atual_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            'fk_documentos_versao_atual',
            'versoes_documento',
            ['versao_atual_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'documento'
    ) as batch_op:

        batch_op.drop_constraint(
            'fk_documentos_versao_atual',
            type_='foreignkey'
        )

        batch_op.drop_column(
            'versao_atual_id'
        )
    # ### end Alembic commands ###
