from enum import Enum

class StatusDocumento(str, Enum):

    PENDENTE_ENVIO = "PENDENTE_ENVIO"
    ENVIADO = "ENVIADO"
    PROCESSANDO = "PROCESSANDO"
    AGUARDANDO_CONFIRMACAO = "AGUARDANDO_CONFIRMACAO"
    EM_ANALISE = "EM_ANALISE"
    APROVADO = "APROVADO"
    REJEITADO = "REJEITADO" 