from enum import Enum

class StatusCandidatura(str, Enum):

    PENDENTE_ENVIO = "PENDENTE_ENVIO"
    AGUARDANDO_PROCESSAMENTO = "AGUARDANDO_PROCESSAMENTO"
    AGUARDANDO_ANALISE = "AGUARDANDO_ANALISE"
    EM_ANALISE = "EM_ANALISE"
    APROVADO = "APROVADO"
    INDEFERIDO = "INDEFERIDO"  