from enum import Enum

class StatusCandidatura(str, Enum):

    AGUARDANDO_DOCUMENTOS = "AGUARDANDO_DOCUMENTOS"
    DOCUMENTACAO_EM_PROCESSAMENTO = "DOCUMENTACAO_EM_PROCESSAMENTO"
    DOCUMENTACAO_PENDENTE = "DOCUMENTACAO_PENDENTE"
    EM_ANALISE = "EM_ANALISE"
    CORRECAO_SOLICITADA = "CORRECAO_SOLICITADA"
    APROVADA = "APROVADA"
    INDEFERIDA = "INDEFERIDA"  